### ISSUE TITLE
Can't enable plugin: myplugin due to cant_create_path

### ISSUE THREAD

**Issue by sunnyjain1** [erlio/vmq_plugin#14]

**Comment by dergraf** [comment]
Can you post the used vmq-admin command?

**Comment by sunnyjain1** [comment]
vmq-admin  plugin enable --name myplugin -p /Users/sunnyjain/Documents/vernemq/_build/default/lib/myplugin

and here is link the code if needed  [myplugin](https://github.com/sunnyjain1/myplugin1)

**Comment by larshesel** [comment]
Hi,

I just did the following and it worked without problems:

```
lhc@georgia ~/temp $ git clone git@github.com:sunnyjain1/myplugin1.git
Cloning into 'myplugin1'...
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 13 (delta 1), reused 13 (delta 1), pack-reused 0
Receiving objects: 100% (13/13), 320.90 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
lhc@georgia ~/temp $ cd myplugin1/
lhc@georgia ~/temp/myplugin1 (master) $ rebar3 compile
lhc@georgia ~/temp/myplugin1 (master) $ vmq-admin plugin enable --name myplugin -p /home/lhc/temp/myplugin1/_build/default/lib/myplugin
Done
lhc@georgia ~/temp/myplugin1 (master) $ vmq-admin plugin show
+-----------+-----------+-----------------+-----------------------------+
|  Plugin   |   Type    |     Hook(s)     |            M:F/A            |
+-----------+-----------+-----------------+-----------------------------+
|vmq_systree|application|                 |                             |
|vmq_passwd |application|auth_on_register |vmq_passwd:auth_on_register/5|
|  vmq_acl  |application| auth_on_publish |  vmq_acl:auth_on_publish/6  |
|           |           |auth_on_subscribe| vmq_acl:auth_on_subscribe/3 |
| myplugin  |application|                 |                             |
+-----------+-----------+-----------------+-----------------------------+
```

The error you see is usually because the path to the plugin is incorrect. Can we get you to double check the path for the plugin and that the application is compiled?

If that's not the problem, can you provide us with some more information such as platform, OS, erlang and vernemq version and maybe a step-by step walk-through of what you did that led to the error?

**Comment by sunnyjain1** [comment]
Thanks It worked. The path I provided is wrong. Sorry for the inconvenience.

**Comment by sunnyjain1** [comment]
Can you tell me 1 more thing unrelated to this topic. How do we register a client on the vernemq server.

I am working on Mac Os X , having Erlang 17.5, I am using vernemq server and mosquitto_pub and mosquitto_sub clients to publish and subscribe  the topic. But when I tried to publish or subscribe it shows authentication problem. I get rid of that by doing allow_anonymous=on But I don't know how to register on the server to get authenticate.

**Comment by ioolkos** [comment]
We use the basic Mosquitto way/tools for doing this.
See the doc:
https://vernemq.com/docs/apps/vmq_passwd/docs/vmq_passwd.html#vmq-passwd
https://vernemq.com/docs/apps/vmq_acl/docs/vmq_acl.html#vmq-acl

The idea is, that any more complex authentication/authorization integration needs a custom plugin anyway.

**Comment by sunnyjain1** [comment]
Okay Thanks.
